server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/cart/**

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payment/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG